### ISSUE TITLE
`# Clone the repo` not working

### ISSUE THREAD

**Issue by wellnoidea** [jlengstorf/learn-rollup#13]
`$ git clone git@github.com:jlengstorf/learn-rollup.git`

will yield

```
Cloning into 'learn-rollup'...
[...]
Permission denied (publickey).
fatal: Could not read from remote repository.
```

---

`$ git clone https://github.com/jlengstorf/learn-rollup`
works just fine

**Comment by jlengstorf** [comment]
That's weird. I've seen this in the past as well, but it seems to be almost arbitrary. I haven't dug into it, though. Does this happen with _all_ repos that you don't own? Or just this one?

If it's all repos, maybe [try the GitHub troubleshooting steps](https://help.github.com/articles/error-permission-denied-publickey/). Maybe your SSH key isn't being passed along?

I'm going to close this since it's more of a GitHub issue than an issue with this tutorial/codebase, but if you end up testing this out and figure anything out, I'd love to hear what you tried and what did/didn't work.
