### ISSUE TITLE
missing index.html

### ISSUE THREAD

**Issue by astropanic** [jlengstorf/learn-rollup#16]
I try to follow the tutorial [How to Bundle JavaScript With Rollup](https://code.lengstorf.com/learn-rollup-js/)

When I run `./node_modules/.bin/rollup -c`

I'm missing the `index.html` file in the `build` directory.

Hence I can't follow the next suggested step:

> We can see that the bundle was created properly by opening build/index.html in our browser:

I watched then the video then instead of the text instructions, and have seen, the files was just added to the build folder for demonstration purpose.

It would be a good idea to write that information as well in the text instructions.

That will save some time for people like me.

**Comment by jlengstorf** [comment]
Thanks for the heads up! I was making the assumption that everyone would clone the starter repo, so that's my bad.

I've [made edits](https://code.lengstorf.com/learn-rollup-js/#step-0-create-a-project-with-javascript-and-css-to-be-compiled) to the directory structure and added a note to help out anyone else who prefers written to video.

Let me know if the edits could be more clear. Thanks again!
