### ISSUE TITLE
error  Strings must use singlequote  quotes

### ISSUE THREAD

**Issue by zhangwei900808** [jlengstorf/learn-rollup#21]
<img width="568" alt="qq20170109-215502 2x" src="https://cloud.githubusercontent.com/assets/4385154/21768810/8c3dc3f2-d6b6-11e6-9df2-8bb376888018.png">

```
/**
 * Says hello.
 * @param  {String} name a name
 * @return {String}      a greeting for `name`
 */
export function sayHelloTo( name ) {
  const toSay = `Hello, ${name}!`;

  return toSay;
}

/**
 * Says goodbye.
 * @param  {String} name a name
 * @return {String}      a farewell for `name`
 */
export function sayGoodbyeTo( name ) {
  const toSay = `Later, ${name}!`;

  return toSay;
}

```

**Comment by jlengstorf** [comment]
It looks like ESLint isn't quite set up correctly. Can you point me to the repo where you're getting this error?

**Comment by zhangwei900808** [comment]
yes, It's found in part-2-starer switch

**Comment by jlengstorf** [comment]
Sorry, I meant your repo — can you link me to your repo that isn't working?

**Comment by stasgavrylov** [comment]
@jlengstorf @zhangwei900808
the problem is not in the repo itself, but rather in the article - https://code.lengstorf.com/learn-rollup-js/
I also stumbled across it, but managed to find a solution. In step 3 "Update `rollup.config.js`" part you put `eslint` plugin after `babel`, but it should be placed before, since in that case it lints the code already transpiled by Babel. I'd sent a PR, but the article is not in the repo :)

Btw, thanks for the tutorial, it's awesome.

**Comment by jlengstorf** [comment]
Thanks, @stasgavrylov! I do keep the articles on GitHub (here's the section you're referencing): https://github.com/jlengstorf/code.lengstorf.com/blob/master/content/blog/learn-rollup-js.md#update-rollupconfigjs-1

If you have time to submit a PR, that would be _very much_ appreciated. Thanks so much for posting the solution here, either way.

**Comment by stasgavrylov** [comment]
@jlengstorf I'm glad I could help, and PR is already waiting. Thanks for pointing me to the article repo.
