### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by ghost** [jlengstorf/learn-rollup#46]
It doesn't open a page or listen the port

**Comment by jlengstorf** [comment]
Hey, @atilkan — can you link to your repo so I can see the code? If I'm unable to see the code that's having problems, I'm unable to help find a solution.

**Comment by ghost** [comment]
It is the same code as this repo.

**Comment by jlengstorf** [comment]
@atilkan There must be an error somewhere because the code in this repo works. I'm going to close this issue for now — if you send over code that produces the error I'll happily reopen and take a look.

One thing to note: running `npm run watch` does not automatically open a page. You need to open the `src/index.html` file in your browser (it will have a URL similar to `file:///Users/jlengstorf/dev/learn-rollup/build/index.html`). This tutorial doesn't cover setting up a server (e.g. `localhost`).

**Comment by ghost** [comment]
@jlengstorf  I understand. It works actually. I did not watch the tuts. Console said there is a port opened, i assumed localhost.
